import '@ispeco/iptl-components-react/es/components/icon/style';
import '@ispeco/iptl-components-react/es/components/button/style';
import '@ispeco/iptl-components-react/es/components/input/style';
import '@ispeco/iptl-components-react/es/components/tabs/style';
import '@ispeco/iptl-components-react/es/components/scroll-panel/style';
import '@ispeco/iptl-components-react/es/components/select/style';
import '@ispeco/iptl-components-react/es/components/input-number/style';
import '@ispeco/iptl-components-react/es/components/color-picker/style';
import '@ispeco/iptl-components-react/es/components/popup/style';